name: Output Test
run-name: Exemplo de Output
on: workflow_dispatch
jobs:
    input:
        runs-on: ubuntu-latest
        outputs:
            hello: ${{ steps.hello.outputs.first }}
            world: ${{ steps.world.outputs.second }}
        steps:
            - name: Super Mario
              id: hello
              run: |
                  echo "first=Super Mario" >> "$GITHUB_OUTPUT"
            - name: World
              id: world
              run: |
                  echo "second=World" >> "$GITHUB_OUTPUT"
    output:
        needs:
            - input
        runs-on: ubuntu-latest
        steps:
            - name: Resultado
              env:
                  hello: ${{ needs.input.outputs.hello }}
                  world: ${{ needs.input.outputs.world }}
              run: echo "$hello $world"
