name: Artifact Test
run-name: Exemplo de Artifact
on: workflow_dispatch
env:
  artifact: arquivo
jobs:
    artifact:
        runs-on: ubuntu-latest
        steps:
            - name: Listagem de arquivos
              run: ls
            - name: Gerar alguns arquivos
              run: |
                  mkdir artifacts
                  echo "Arquivo de teste" > ./artifacts/test.txt
            - name: Upload a Build Artifact
              id: upload
              uses: actions/upload-artifact@v7.0.1
              with:
                name: ${{ env.artifact }}
                path: ./artifacts
            - name: Endereço dos artefatos
              run: |
                  echo "${{ steps.upload.outputs.artifact-url }}
    download:
        runs-on: ubuntu-latest
        needs:
          - artifact
        steps:
          - name: Listagem de arquivos
            run: ls
          - name: Download Artifact
            uses: actions/download-artifact@v8
            with:
                name: ${{ env.artifact }}
          - name: Display structure of downloaded files
            run: ls -R
